### ISSUE TITLE
packageManager can Specify a range of versions

### ISSUE THREAD

**Issue by SnowingFox** [nodejs/corepack#208] opened 2022-11-05 08:05 UTC
### What is the problem this feature will solve?

now we just can specify a exact version, but in some case we want to specify a range of version

### What is the feature you are proposing to solve the problem?

```bash
"packageManger": "pnpm@7"
```

it means that your pnpm version is need bigger that `7.0.0`

or we can specify a range

```bash
"packageManger":  "pnpm@>=7.1.0"
```

### What alternatives have you considered?

i use [@antfu/ni](https://github.com/antfu/ni) to solve my problem, but i still hope the offical can solve it.

**Comment by aduh95** [comment] 2022-11-05 15:44
Duplicate of https://github.com/nodejs/corepack/issues/95, let's continue the discussion there.

**Closed by aduh95** 2022-11-05 15:44 UTC
