### ISSUE TITLE
`packageManager` should accept a version range

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/corepack#404] opened 2024-02-27 06:28 UTC
Just as `engines` supports values like `>= 10.0.0`, I should be able to tell Corepack that I want a particular version range rather than only being allowed to pin a precise version.

Split off from #402.

**Comment by aduh95** [comment] 2024-02-27 06:46
Duplicate of https://github.com/nodejs/corepack/issues/95

**Closed by aduh95** 2024-02-27 06:46 UTC
Labels: enhancement
