### ISSUE TITLE
Allow setting packageManager to range, similar to `engines.npm`

### ISSUE THREAD

**Issue by mehulkar** [nodejs/corepack#315] opened 2023-10-11 19:28 UTC
I would like to be able to set `packageManager` field with a non-specific version. Roughly speaking it should allow whatever is allowed by `engines.npm`. 

This is similar to #298, but wasn't sure if it's the same request.

**Comment by styfle** [comment] 2023-10-11 19:34
This looks like a duplicate of https://github.com/nodejs/corepack/issues/95

**Closed** 2023-10-11 20:39 UTC
