### ISSUE TITLE
Internal Error while executing any yarn command...

### ISSUE THREAD

**Issue by from-nobody** [nodejs/corepack#273] opened 2023-06-02 10:35 UTC
I cloned a project via and tried to execute 'yarn install' to install dependencies but got an error as followed .Whatever command I typed, it just thrown the same Internal Error.
As a contrast , I cloned another yarn-based project, and everything went OK.

**Expectation: Run target project locally.**

The target project gitignore is:
`.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions

!.yarn/cache
node_modules/`

****************************************
`PS C:\Users\user_name\test\project_cloned_from_github> yarn config

Internal Error: Error when performing the request
    at ClientRequest.<anonymous> (D:\Program Files\nodejs\node_modules\corepack\dist\corepack.js:43953:14)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

************************************************************
PS C:\Users\user_name\test\project_cloned_from_github> yarn -v

Internal Error: Error when performing the request
    at ClientRequest.<anonymous> (D:\Program Files\nodejs\node_modules\corepack\dist\corepack.js:43953:14)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)`

**Comment by aduh95** [comment] 2023-06-02 13:04
Duplicate of https://github.com/nodejs/corepack/issues/257?

**Closed** 2023-06-13 04:22 UTC
