### ISSUE TITLE
npm 9.7.0 and newer fails with "segmentation fault"

### ISSUE THREAD

**Issue by styfle** [nodejs/corepack#288] opened 2023-07-19 19:06 UTC
## Steps to reproduce

1. Install Node.js v18.16.0 on macOS (arm) (See official [download](https://nodejs.org/dist/v18.16.0/node-v18.16.0.pkg))
1. Run `corepack prepare npm@9.7.0 --activate`
1. Run `npm --version`
1. Notice error `[1]    68100 segmentation fault  npm --version`

It works with `npm@9.6.7` but started failing with every version since `npm@9.7.0`.

**Comment by merceyz** [comment] 2023-07-19 19:21
Duplicate of https://github.com/nodejs/corepack/issues/277

**Closed by merceyz** 2023-07-19 19:21 UTC

**Comment by styfle** [comment] 2023-07-19 19:35
Thanks! Is there a Node.js PR to update this in 18.x that I can follow along?

**Comment by aduh95** [comment] 2023-07-19 22:12
Node.js 18.x is an Active LTS line, meaning commits are "automatically" backported to it after a maturation period. It didn’t make it to 18.17.0, it should be on the next non-security one.
