### ISSUE TITLE
Unhandled Exception leading to Ambiguous and Unhelpful 404 Error | Corepack 

### ISSUE THREAD

**Issue by jeremiah-snee-openx** [nodejs/corepack#203] opened 2022-11-01 01:57 UTC
Issue reported in node repo

[#45262](https://github.com/nodejs/corepack/issues/204)

**Comment by aduh95** [comment] 2022-11-01 02:23
Duplicate of https://github.com/nodejs/corepack/issues/204.

**Closed by aduh95** 2022-11-01 02:23 UTC
