### ISSUE TITLE
Corepack error with yarn on enable

### ISSUE THREAD

**Issue by MP185496** [nodejs/corepack#450] opened 2024-04-05 10:10 UTC
I enabled corepack and when i tried to install modules by running yarn i got this error
Type Error: URL.canParse is not a function
    at parseSpec (/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/corepack/dist/lib/corepack.cjs:23359:21)
    at loadSpec (/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/corepack/dist/lib/corepack.cjs:23422:11)
    at async InstallLocalCommand.resolvePatternsToDescriptors (/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/corepack/dist/lib/corepack.cjs:23894:22)
    at async InstallLocalCommand.execute (/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/corepack/dist/lib/corepack.cjs:24030:26)
    at async InstallLocalCommand.validateAndExecute (/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/corepack/dist/lib/corepack.cjs:21164:22)
    at async _Cli.run (/Users/mp185496/.nvm/versions/node/v18.15.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22139:18)
    at async Object.runMain (/Users/user/.nvm/versions/node/v18.15.0/lib/node_modules/corepack/dist/lib/corepack.cjs:24355:12)

**Comment by styfle** [comment] 2024-04-05 12:33
You are running an old version of Node.js 

You’ll need to upgrade

**Comment by aduh95** [comment] 2024-04-06 16:52
Duplicate of https://github.com/nodejs/corepack/issues/394

My recommendation is to upgrade the version of Node.js you're using, but you can also check the other issues for alternative solutions.

**Closed by aduh95** 2024-04-06 16:52 UTC
